### PR TITLE
HTTPProjectConfigManager: datafile should be a string

### PR DESCRIPTION
**Pull request by adri**
## Summary
- By using `->getContents()` the actual string is returned instead of a Guzzle Stream object. The interface uses string everywhere.

### CODE REVIEW

**Review by msohailhussain — COMMENTED** [review]
changes seem fine to me. Let's do our internal testing and will merge if it is passed.

**Comment by adri** [comment]
Thanks a lot for looking into this @msohailhussain. I tested it in our project. Is there already and update on internal testing? :) Thanks again!

**Comment by msohailhussain** [comment]
@adri Please sign the CLA. 
https://docs.google.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform

**Review by msohailhussain — CHANGES_REQUESTED** [review]
PR looks good, please update the Copyright header.

**Comment by msohailhussain** [comment]
@adri waiting for CLA and one change request. Also update the branch.

**Comment by adri** [comment]
@msohailhussain Done!

**Review by msohailhussain — APPROVED** [review]
lgtm!!! need to update copyright header.

**Pull request merged**
