### PR TITLE
1.5.0

### PR DESCRIPTION
**Pull request by alda-optimizely**
Cherry-picked ip anonymization and notification listeners from master.
1.5.x is based off the 1.4.0 release (no 1.4.x branch was made).

### CODE REVIEW

**Comment by mikeng13** [comment]
build

**Comment by alda-optimizely** [comment]
@oakbani Hey Owais, I'm preparing a 1.5.0 release and I've cherry-picked the notification listeners and IP anonymization onto the 1.4.0 release. I need your help with making sure that the cherry-pick was clean as there were a number of conflicts. There are also a few unit tests failing since the datafiles are different. Would you be able to take a look? Thanks!

**Comment by oakbani** [comment]
Sure, I will let you know on Monday

**Comment by msohailhussain** [comment]
@alda-optimizely https://github.com/optimizely/php-sdk/pull/80
Please check this PR, it should resolve conflicts of this PR.

**Comment by alda-optimizely** [comment]
thanks @oakbani!

**Comment by mikeng13** [comment]
build

**Comment by mikeng13** [comment]
build

**Comment by alda-optimizely** [comment]
I checked the notification listener e2e tests locally and everything passes.

**Pull request merged**
