### PR TITLE
Add prefix to PSR-4 autoloader

### PR DESCRIPTION
**Pull request by dcloues**
PSR-4 autoloaders with no prefix can hurt performance, especially in large projects with many dependencies. When resolving class names to files, if Composer cannot use a prefix to limit the search paths, it has to search every autoloader with a blank prefix.

This change adds a prefix to the autoloader, to avoid this problem.

Running `composer diagnose` previously reported this:

```
~/src/php-sdk % composer diagnose
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
```

With this change, `composer diagnose` is happy.

I couldn't add tests for this, because it's not a code change. But, I did run the test suite to verify that it everything still passes as expected.

### CODE REVIEW

**Comment by aliabbasrizvi** [comment]
Hi @dcloues , thank you for submitting this fix. I'd like to request you to fill out our CLA mentioned here: https://github.com/optimizely/php-sdk/blob/master/CONTRIBUTING.md#contributing-to-the-optimizely-php-sdk

Once done, I shall be able to get this in.

Thank you again.

**Comment by dcloues** [comment]
Hi @aliabbasrizvi - thanks so much! Sorry for missing the CLA the first time around - I read the contributing guide and somehow read right past it, even though it's super clear. I just submitted the agreement - thanks again.

**Comment by aliabbasrizvi** [comment]
build

**Comment by aliabbasrizvi** [comment]
build

**Comment by aliabbasrizvi** [comment]
Thanks @dcloues for sending this in. Changes look good. I am going to merge this in and it will hopefully be available in the next release 🙂.

**Pull request merged**
