### PR TITLE
PHP Documentor Config File

### PR DESCRIPTION
**Pull request by oakbani**
The generated docs along with instructions have been pushed to **gh-pages** branch.

### CODE REVIEW

**Comment by tylerbrandt** [comment]
build

**Comment by tylerbrandt** [comment]
build

**Comment by msohailhussain** [comment]
@mikeng13 @tylerbrandt Do you know why testapp is getting failed?

**Comment by oakbani** [comment]
@mikeng13 These are general instructions that should work for any checked out branch be it latest or some other 1.x version. The generated docs/api folder will have to be copied in the appropriate version folder inside gh-pages branch. 

Yeah, the meta-tags such as @internal need to be committed separately to each version branch. For now, I put meta tags locally and generated docs.

**Comment by aliabbasrizvi** [comment]
Closing. Re-open if needed.

**Pull request closed without merging**
