### PR TITLE
fix: avoid deprecation notices in php 8.1 when passing null to strlen

### PR DESCRIPTION
**Pull request by drieschel**
The following deprecation notice is popping up in conjunction with php 8.1 when calling `$optimizelyClient->setForcedVariation(...);` and the experiment is not active for the related environment.

> PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /path/to/project/vendor/optimizely/optimizely-sdk/src/Optimizely/DecisionService/DecisionService.php on line 557

In order to fix this it is necessary to cast `$experimentId` and `$variationId` to string when passing them to `strlen(...)` function in `Optimizely\DecisionService\DecisionService::setForcedVariation` method.

Detailed infos about the deprecation notice can be found here: https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

### CODE REVIEW

**Comment by drieschel** [comment]
Hello @mikechu-optimizely,

I saw you reviewed another PR. Can you also check this one or add the right reviewers? In case something is missing for a proper PR please let me know, so I will be able to fix that.

**Comment by mikechu-optimizely** [comment]
Hi @drieschel,

Thanks for giving us your time and expertise.  

I've forwarded this into our queue as well as notified our SDK Manager and PHP dev (you don't want *me* reviewing 😁). 

Apologies for the delayed response, but look for me to reply within the next week or feel free to (a)mention me as well.

Back shortly,
Mike

**Comment by mikechu-optimizely** [comment]
Hi @drieschel,

I'm bringing up your PR in our stand-up meeting today.

Expect to hear from me today or tomorrow with at least an update.

Thanks for your patience.  

--Mike

**Comment by mikechu-optimizely** [comment]
Hi Again @drieschel,

We've added this Pull Request into our next sprint for review. 

While we're moving the task forward, please review the [Contributing.md](https://github.com/optimizely/php-sdk/blob/master/CONTRIBUTING.md). We'll need you to sign the Contributor License Agreement (CLA) linked in that file.

Thanks,
Mike

**Comment by drieschel** [comment]
Thank you @mikechu-optimizely! I signed the CLA. Please let me know if you need anything else from my side.

**Comment by mikechu-optimizely** [comment]
I see your information and agreement.  Danke. 

Please look towards an update within the next 2 weeks (hopefully less) during our next sprint.

**Comment by mikechu-optimizely** [comment]
Well, I guess you are stuck with me.  The task item showed up on my board for this next sprint.  Time to go brush off my old PHP skills.

My tasking is to research the effect of this change, along with running tests on your solution (direct cast). Thanks for providing the resource/research in your original submission. 

Back w/ you this week on this....

**Comment by drieschel** [comment]
Thanks for keeping me updated @mikechu-optimizely and sorry for the inconveniences.

**Comment by mikechu-optimizely** [comment]
No inconvenience at all. Thanks for taking the time to contribute.

**Review by msohailhussain — APPROVED** [review]
lgtm
let me check with our integration tests and we are good to go.

**Pull request merged**
