### PR TITLE
Allow monolog versions >= 1.21

### LINKED ISSUE #31: monolog version
Hey there,

do we really need to fix monolog/monolog to a specific version? As of right now the sdk requires version ```1.21.0``` and I would be surprised if something like ```^1.21.0``` doesn't work as well. 

Best,
Daniel

### PR DESCRIPTION
**Pull request by Spea**
This will fix #31

### CODE REVIEW

**Comment by Spea** [comment]
Done

**Comment by aliabbasrizvi** [comment]
Cool, thanks for doing that. I notice that you are trying to merge into `master`. We need to merge it in `devel` first and then for the next release we will merge into `master` as there are some other changes as well.

**Comment by Spea** [comment]
Rebased onto devel and changed base branch, sorry for the inconvenience

**Comment by aliabbasrizvi** [comment]
Thanks for doing that @Spea 

Will ping you when we have a release going. It should be in the next couple of days.

**Pull request merged**
